### ISSUE TITLE
[Bug] Icon disappearing on sidebar

### ISSUE THREAD

**Issue by Nick2bad4u** [Thource/dude-wheres-my-stuff#94] opened 2023-03-12 19:50 UTC
![image](https://user-images.githubusercontent.com/20943337/224569522-cb5431b1-ee3b-4b18-a081-4625da207e3d.png)
This happens every so often, not sure why.

Rebooting usually fixes it.

Sometimes going into the settings and selecting a new sidebar icon fixes it:

![image](https://user-images.githubusercontent.com/20943337/224569570-570d2186-6fcf-4caa-98de-6f672f52fb34.png)

But even some of those don't show up properly:

![image](https://user-images.githubusercontent.com/20943337/224569599-1ef23e9e-ae83-4d8b-88e1-be0509206cf8.png)

**Comment by Thource** [comment] 2023-03-12 19:56
Hey, thanks for your detailed report, this is a duplicate of #32, I’ve made a fix for this, waiting for the RL guys to approve it but it could take a few weeks :)

https://github.com/runelite/plugin-hub/pull/4029

**Closed** 2023-04-03 20:43 UTC
Labels: bug, duplicate, awaiting release
